version: "3"
services:
  postgres:
    container_name: postgres_misfits
    image: postgres:14
    ports:
    - "5555:5432"
    volumes:
    - postgresdata:/data/postgres_misfits
    - postgresdbdata:/var/lib/postgresql_misfits/data
    env_file:
    - docker.env


volumes:
  postgresdata:
    driver: local
  postgresdbdata:
    driver: local
