export enum Status {
    APPLIED = 'APPLIED',
    HR_PENDING = 'HR_PENDING',
    HR_ACCEPTED = 'HR_ACCEPTED',
    HR_REJECTED = 'HR_REJECTED',
    PENDING_TIMESLOT_SUBMISSION = 'PENDING_TIMESLOT_SUBMISSION',
    TIMESLOT_SUBMITTED = 'TIMESLOT_SUBMITTED',
    PENDING_INTERVIEWER_CONFIRMATION = 'PENDING_INTERVIEWER_CONFIRMATION',
    INTERVIEWER_REJECTED = 'INTERVIEWER_REJECTED',
    INTERVIEW_SCHEDULED = 'INTERVIEW_SCHEDULED',
    PENDING_INTERVIEW_FEEDBACK = 'PENDING_INTERVIEW_FEEDBACK',
    INTERVIEW_FEEDBACK_SUBMITTED = 'INTERVIEW_FEEDBACK_SUBMITTED',
    CANDIDATE_ACCEPTED = 'CANDIDATE_ACCEPTED',
    CANDIDATE_REJECTED = 'CANDIDATE_REJECTED',
}

export enum EventStatus {
    COMPLETED = "COMPLETED",
    PENDING = "PENDING",
    ACCEPETED = "ACCEPTED",
    REJECTED = "REJECTED",
}