export enum ApplicationEvents {
    APPLIED = "APPLIED",
    HR_REVIEW = "HR_REVIEW",
    INTERVIEWER_REVIEW = "INTERVIEWER_REVIEW",
    INTERVIEW_FEEDBACK = "INTERVIEW_FEEDBACK",
    ACCEPTED = "ACCEPTED",
    REJECTED = "REJECTED",
}